project:
  type: website

website:
  title: "ViennaR"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ViennaR
      - icon: calendar
        href: https://www.meetup.com/ViennaR/
format:
  html:
    theme: default # potential picks: default, litera, simplex, spacelab
    css: styles.css
