# .github/workflows/render-and-publish.yaml
name: Render and deploy Quarto files
on:
  push:
    branches:
      - main

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1

      - name: "Install curl for Bioconductor"
        run: |
          sudo apt -y install libcurl4-openssl-dev

      - name: "Install R Packages: Cache packages"
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: "Install R Packages: Restore packages"
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: "Download Quarto"
        shell: bash
        run: |
          # Hardcoding versions for now to make sure new versions don't break things
          quarto_version="0.9.545"
          quarto_file_name="quarto-${quarto_version}-linux-amd64.deb"
          quarto_url="https://github.com/quarto-dev/quarto-cli/releases/download/v${quarto_version}/${quarto_file_name}"
          wget -q "${quarto_url}"
          sudo dpkg -i "${quarto_file_name}"
    
      - name: "Quarto render"
        shell: bash
        run: |
          quarto render --execute-debug

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./_site ${{ secrets.AWS_BUCKET }} --delete
